# Project Language
language: python
python:
  - "2.7"

# Dependencies Installation
install:
  - pip install -r requirements.txt
  - pip install coveralls

# Testing
script:
  coverage run manage.py test

# Coveralls
after_success:
  Coveralls

# Slack
notifications:
  slack: apipanda:UNJdlVzsjpL85Aw6dys1hZZE


