# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-27 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160304_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationModel',
        ),
    ]
