# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-19 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ssl_certificate', models.CharField(max_length=200)),
                ('ssl_key', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('date_registered', models.DateField()),
                ('expiration_date', models.DateField()),
                ('last_updated', models.DateField()),
            ],
        ),
    ]
