# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-16 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='date_registered',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='last_updated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
