# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-16 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_auto_20160616_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='ssl_certificate',
            field=models.CharField(max_length=255),
        ),
    ]
