# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-16 00:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='top_level_domain',
            new_name='tld',
        ),
        migrations.AddField(
            model_name='domain',
            name='admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='domains', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='slug',
            field=models.SlugField(default='example-com', max_length=100),
            preserve_default=False,
        ),
    ]
