# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-16 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_auto_20160616_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='support_email',
            field=models.EmailField(max_length=200),
        ),
    ]
