# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-16 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_auto_20160616_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
