# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-16 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_auto_20160616_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certified_domain', to='certificate.Certificate'),
        ),
    ]
