# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-04 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0005_auto_20160616_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='verification_type',
            field=models.CharField(choices=[(b'C', b'CNAME'), (b'F', b'File Upload'), (b'T', b'TXT Record')], default='T', max_length=16),
            preserve_default=False,
        ),
    ]
