# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-12 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0006_domain_verification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain_registerer',
            new_name='domain_registrar',
        ),
        migrations.AlterField(
            model_name='domain',
            name='verification_type',
            field=models.CharField(choices=[(b'C', b'CNAME'), (b'F', b'File Upload'), (b'T', b'TXT Record'), (b'M', b'Meta Tag')], max_length=16),
        ),
    ]
